-- 002_seed_cars.sql — реальный автопарк NSK-RENT (21 автомобиль).
-- Идемпотентно: повторный запуск ничего не дублирует (on conflict do nothing по slug).

insert into cars (slug, brand, model, year, class, transmission, seats, price_city, price_out, status, images, specs, plate)
values
  ('honda-n-wgn-grey-1','Honda','N-WGN',2020,'Econom','AT',4,1800,2050,'available',
   '["/assets/cars/honda-n-wgn-grey.jpg"]'::jsonb,
   '{"color":"серый","engineVolume":0.66,"consumption":3.9,"power":58,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.8,"reviewsCount":42}'::jsonb,
   'Т987ТТ154'),
  ('honda-n-wgn-blue-1','Honda','N-WGN',2020,'Econom','AT',4,1800,2050,'available',
   '["/assets/cars/honda-n-wgn-blue.jpg"]'::jsonb,
   '{"color":"синий","engineVolume":0.66,"consumption":4.0,"power":58,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.7,"reviewsCount":31}'::jsonb,
   'Т298РМ154'),
  ('honda-n-wgn-blue-2','Honda','N-WGN',2020,'Econom','AT',4,1850,2100,'available',
   '["/assets/cars/honda-n-wgn-blue.jpg"]'::jsonb,
   '{"color":"синий","engineVolume":0.66,"consumption":3.9,"power":58,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.7,"reviewsCount":24}'::jsonb,
   'Т767РТ154'),
  ('honda-n-wgn-black-1','Honda','N-WGN',2020,'Econom','AT',4,1900,2150,'busy',
   '["/assets/cars/honda-n-wgn-black.jpg"]'::jsonb,
   '{"color":"чёрный","engineVolume":0.66,"consumption":3.8,"power":58,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.9,"reviewsCount":56}'::jsonb,
   'Х498АЕ154'),
  ('nissan-dayz-green-1','Nissan','Dayz',2020,'Econom','AT',4,1800,2050,'available',
   '["/assets/cars/nissan-dayz-green.jpg"]'::jsonb,
   '{"color":"зелёный","engineVolume":0.66,"consumption":3.7,"power":52,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.6,"reviewsCount":18}'::jsonb,
   'Х765ВА154'),
  ('nissan-dayz-brown-1','Nissan','Dayz',2020,'Econom','AT',4,1800,2050,'available',
   '["/assets/cars/nissan-dayz-brown.jpg"]'::jsonb,
   '{"color":"коричневый","engineVolume":0.66,"consumption":3.6,"power":52,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.6,"reviewsCount":21}'::jsonb,
   'Х164ВТ154'),
  ('mitsubishi-ek-wagon-blue-1','Mitsubishi','eK Wagon',2020,'Econom','AT',4,1800,2000,'available',
   '["/assets/cars/mitsubishi-ek-wagon-blue.jpg"]'::jsonb,
   '{"color":"синий","engineVolume":0.66,"consumption":3.8,"power":49,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.5,"reviewsCount":16}'::jsonb,
   'Х776АА154'),
  ('daihatsu-mira-es-black-1','Daihatsu','Mira e:S',2021,'Econom','AT',4,1900,2150,'available',
   '["/assets/cars/daihatsu-mira-es-black.jpg"]'::jsonb,
   '{"color":"чёрный","engineVolume":0.66,"consumption":3.6,"power":49,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.8,"reviewsCount":33}'::jsonb,
   'Т656ХМ154'),
  ('nissan-dayz-grey-1','Nissan','Dayz',2021,'Econom','AT',4,1900,2150,'available',
   '["/assets/cars/nissan-dayz-grey.jpg"]'::jsonb,
   '{"color":"серый","engineVolume":0.66,"consumption":3.8,"power":52,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.8,"reviewsCount":29}'::jsonb,
   'Х602МВ154'),
  ('nissan-dayz-white-1','Nissan','Dayz',2021,'Econom','AT',4,2000,2250,'busy',
   '["/assets/cars/nissan-dayz-white.jpg"]'::jsonb,
   '{"color":"белый","engineVolume":0.66,"consumption":3.7,"power":52,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.9,"reviewsCount":47}'::jsonb,
   'К330ХО122'),
  ('daihatsu-move-white-1','Daihatsu','Move',2013,'Econom','AT',4,1800,2000,'available',
   '["/assets/cars/daihatsu-move-white.jpg"]'::jsonb,
   '{"color":"белый","engineVolume":0.66,"consumption":4.6,"power":52,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.4,"reviewsCount":14}'::jsonb,
   'Т370ХХ154'),
  ('honda-n-wgn-white-1','Honda','N-WGN',2021,'Econom','AT',4,2000,2250,'available',
   '["/assets/cars/honda-n-wgn-white.jpg"]'::jsonb,
   '{"color":"белый","engineVolume":0.66,"consumption":3.8,"power":58,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.9,"reviewsCount":38}'::jsonb,
   'Х117ЕТ154'),
  ('honda-n-wgn-turbo-white-1','Honda','N-WGN Turbo',2014,'Econom','AT',4,2100,2400,'available',
   '["/assets/cars/honda-n-wgn-turbo-white.jpg"]'::jsonb,
   '{"color":"белый","engineVolume":0.66,"consumption":5.0,"power":64,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.7,"reviewsCount":26}'::jsonb,
   'Р197РН70'),
  ('honda-n-wgn-white-2','Honda','N-WGN',2020,'Econom','AT',4,1900,2150,'available',
   '["/assets/cars/honda-n-wgn-white.jpg"]'::jsonb,
   '{"color":"белый","engineVolume":0.66,"consumption":3.9,"power":58,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.7,"reviewsCount":22}'::jsonb,
   'Н776ЕН13'),
  ('nissan-dayz-grey-2','Nissan','Dayz',2013,'Econom','AT',4,1800,2000,'available',
   '["/assets/cars/nissan-dayz-grey.jpg"]'::jsonb,
   '{"color":"серый","engineVolume":0.66,"consumption":4.4,"power":49,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.4,"reviewsCount":11}'::jsonb,
   'М616НМ45'),
  ('honda-n-box-black-1','Honda','N-BOX',2020,'Econom','AT',4,2100,2400,'busy',
   '["/assets/cars/honda-n-box-black.jpg"]'::jsonb,
   '{"color":"чёрный","engineVolume":0.66,"consumption":4.8,"power":58,"bodyType":"минивэн","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.9,"reviewsCount":61}'::jsonb,
   'Т960РУ154'),
  ('nissan-dayz-black-1','Nissan','Dayz',2013,'Econom','AT',4,1800,2000,'available',
   '["/assets/cars/nissan-dayz-black.jpg"]'::jsonb,
   '{"color":"чёрный","engineVolume":0.66,"consumption":4.3,"power":49,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.5,"reviewsCount":17}'::jsonb,
   'Т847ВА154'),
  ('daihatsu-mira-white-1','Daihatsu','Mira (3 двери)',2015,'Econom','AT',4,1800,2000,'available',
   '["/assets/cars/daihatsu-mira-white.jpg"]'::jsonb,
   '{"color":"белый","engineVolume":0.66,"consumption":4.1,"power":49,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.4,"reviewsCount":9}'::jsonb,
   'М663ХМ154'),
  ('suzuki-alto-white-1','Suzuki','Alto',2011,'Econom','AT',4,1800,2000,'available',
   '["/assets/cars/suzuki-alto-white.jpg"]'::jsonb,
   '{"color":"белый","engineVolume":0.66,"consumption":4.2,"power":49,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.3,"reviewsCount":12}'::jsonb,
   'Х839АХ154'),
  ('daihatsu-mira-es-white-1','Daihatsu','Mira e:S',2021,'Econom','AT',4,1900,2150,'available',
   '["/assets/cars/daihatsu-mira-es-white.jpg"]'::jsonb,
   '{"color":"белый","engineVolume":0.66,"consumption":3.6,"power":49,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.8,"reviewsCount":35}'::jsonb,
   'Т423УМ154'),
  ('suzuki-alto-white-2','Suzuki','Alto',2010,'Econom','AT',4,1800,2000,'available',
   '["/assets/cars/suzuki-alto-white.jpg"]'::jsonb,
   '{"color":"белый","engineVolume":0.66,"consumption":4.3,"power":49,"bodyType":"хэтчбек","deposit":2000,"mileageLimit":300,"fuelPolicy":"полный → полный","drive":"передний","rating":4.3,"reviewsCount":8}'::jsonb,
   'Х464КУ125')
on conflict (slug) do nothing;
