import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Download, FileText, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { getMyContractData } from "@/lib/profile.functions";
import { PICKUP_POINT } from "@/mocks/pickupPoints";
import { getTariff } from "@/mocks/tariffs";
import { SectionCard } from "@/components/checkout/SectionCard";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/_public/contract/$bookingId")({ head: () => ({ meta: [{ title: "Договор аренды — NSK-RENT" }, { name: "description", content: "Подписанный договор аренды автомобиля NSK-RENT." }, { property: "og:title", content: "Договор аренды — NSK-RENT" }, { property: "og:description", content: "Реквизиты и условия договора аренды." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }, { name: "robots", content: "noindex, nofollow" }] }), component: ContractPage });
function ContractPage() {
  const { bookingId } = Route.useParams(); const load = useServerFn(getMyContractData);
  const { data, isLoading } = useQuery({ queryKey: ["me", "contract", bookingId], queryFn: () => load({ data: { bookingId } }) });
  if (isLoading) return <div className="flex min-h-[45vh] items-center justify-center"><Loader2 className="mr-2 h-5 w-5 animate-spin" />Загружаем договор…</div>;
  if (!data) return <div className="py-12 text-center"><h1 className="text-xl font-semibold">Договор не найден</h1><Button asChild className="mt-4"><Link to="/profile/rentals">К арендам</Link></Button></div>;
  const passport = data.documents.find((document) => document.type === "passport"); const license = data.documents.find((document) => document.type === "license");
  const lines = ["ДОГОВОР АРЕНДЫ ТРАНСПОРТНОГО СРЕДСТВА", `Номер брони: ${data.id}`, `Арендатор: ${data.client.name}`, `Телефон: ${data.client.phone}`, `E-mail: ${data.client.email || "—"}`, `Паспорт: ${passport?.number || "не указан"}`, `Дата рождения: ${passport?.birthDate || "не указана"}`, `Выдан: ${passport?.issuedBy || "не указано"}`, `Дата выдачи: ${passport?.issueDate || "не указана"}, код ${passport?.departmentCode || "—"}`, `Адрес регистрации: ${passport?.registrationAddress || "не указан"}`, `Водительское удостоверение: ${license?.number || "не указано"}`, `Выдано: ${license?.issueDate || "—"}, действительно до ${license?.expiryDate || "—"}`, `Автомобиль: ${data.car.brand} ${data.car.model}, ${data.car.year}, ${data.car.color}, ${data.car.plate}`, `Период: ${format(data.startDate)} — ${format(data.endDate)}`, `Тариф: ${getTariff(data.tariff === "region" || data.tariff === "outside" ? data.tariff : "city").title}`, `Пункт выдачи: ${PICKUP_POINT.address}`, `Стоимость: ${data.totalPrice.toLocaleString("ru-RU")} ₽`, "", "Договор подписан простой электронной подписью (код из SMS) на сайте NSK-RENT."];
  const download = () => { const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `dogovor-${data.id}.txt`; anchor.click(); URL.revokeObjectURL(url); toast.success("Договор скачан"); };
  return <div className="mx-auto max-w-xl space-y-4"><div><h1 className="text-2xl font-semibold">Договор аренды</h1><p className="text-sm text-muted-foreground">Данные сформированы из вашей подтверждённой брони.</p></div><SectionCard title="Стороны и документы" className="bg-card ring-1 ring-border"><dl className="space-y-2 text-sm"><Row label="Арендатор" value={data.client.name} /><Row label="Паспорт" value={passport?.number || "Заполните в кабинете"} /><Row label="Водительское удостоверение" value={license?.number || "Заполните в кабинете"} /></dl></SectionCard><SectionCard title="Автомобиль и срок" className="bg-card ring-1 ring-border"><dl className="space-y-2 text-sm"><Row label="Автомобиль" value={`${data.car.brand} ${data.car.model}, ${data.car.year}`} /><Row label="Период" value={`${format(data.startDate)} — ${format(data.endDate)}`} /><Row label="Пункт выдачи" value={PICKUP_POINT.address} /><Row label="Стоимость" value={`${data.totalPrice.toLocaleString("ru-RU")} ₽`} /></dl></SectionCard><Button className="w-full" onClick={download}><Download className="mr-2 h-4 w-4" />Скачать договор</Button><Button asChild variant="outline" className="w-full"><Link to="/profile/documents"><FileText className="mr-2 h-4 w-4" />Изменить данные документов</Link></Button></div>;
}
function format(value: string) { return new Date(value).toLocaleString("ru-RU", { day: "2-digit", month: "long", year: "numeric", hour: "2-digit", minute: "2-digit" }); }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex items-start justify-between gap-4"><dt className="text-muted-foreground">{label}</dt><dd className="text-right font-medium">{value}</dd></div>; }