/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as PublicTermsRouteImport } from './routes/_public.terms'
import { Route as PublicProfileRouteImport } from './routes/_public.profile'
import { Route as PublicPrivacyRouteImport } from './routes/_public.privacy'
import { Route as PublicKeiCarsRouteImport } from './routes/_public.kei-cars'
import { Route as PublicCarsIndexRouteImport } from './routes/_public.cars.index'
import { Route as PublicBlogIndexRouteImport } from './routes/_public.blog.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as PublicRentNovosibirskRouteImport } from './routes/_public.rent.novosibirsk'
import { Route as PublicRentBezZalogaRouteImport } from './routes/_public.rent.bez-zaloga'
import { Route as PublicPaymentBookingIdRouteImport } from './routes/_public.payment.$bookingId'
import { Route as PublicContractBookingIdRouteImport } from './routes/_public.contract.$bookingId'
import { Route as PublicCarsCarIdRouteImport } from './routes/_public.cars.$carId'
import { Route as PublicBookingCarIdRouteImport } from './routes/_public.booking.$carId'
import { Route as PublicBlogSlugRouteImport } from './routes/_public.blog.$slug'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminFinanceRouteImport } from './routes/_admin.admin.finance'
import { Route as AdminAdminClientsRouteImport } from './routes/_admin.admin.clients'
import { Route as AdminAdminCarsRouteImport } from './routes/_admin.admin.cars'
import { Route as AdminAdminBookingsRouteImport } from './routes/_admin.admin.bookings'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProfileRoute = PublicProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicKeiCarsRoute = PublicKeiCarsRouteImport.update({
  id: '/kei-cars',
  path: '/kei-cars',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCarsIndexRoute = PublicCarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicRentNovosibirskRoute = PublicRentNovosibirskRouteImport.update({
  id: '/rent/novosibirsk',
  path: '/rent/novosibirsk',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRentBezZalogaRoute = PublicRentBezZalogaRouteImport.update({
  id: '/rent/bez-zaloga',
  path: '/rent/bez-zaloga',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPaymentBookingIdRoute = PublicPaymentBookingIdRouteImport.update({
  id: '/payment/$bookingId',
  path: '/payment/$bookingId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContractBookingIdRoute = PublicContractBookingIdRouteImport.update({
  id: '/contract/$bookingId',
  path: '/contract/$bookingId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCarsCarIdRoute = PublicCarsCarIdRouteImport.update({
  id: '/cars/$carId',
  path: '/cars/$carId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBookingCarIdRoute = PublicBookingCarIdRouteImport.update({
  id: '/booking/$carId',
  path: '/booking/$carId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminFinanceRoute = AdminAdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminClientsRoute = AdminAdminClientsRouteImport.update({
  id: '/admin/clients',
  path: '/admin/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCarsRoute = AdminAdminCarsRouteImport.update({
  id: '/admin/cars',
  path: '/admin/cars',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBookingsRoute = AdminAdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kei-cars': typeof PublicKeiCarsRoute
  '/privacy': typeof PublicPrivacyRoute
  '/profile': typeof PublicProfileRoute
  '/terms': typeof PublicTermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/bookings': typeof AdminAdminBookingsRoute
  '/admin/cars': typeof AdminAdminCarsRoute
  '/admin/clients': typeof AdminAdminClientsRoute
  '/admin/finance': typeof AdminAdminFinanceRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/booking/$carId': typeof PublicBookingCarIdRoute
  '/cars/$carId': typeof PublicCarsCarIdRoute
  '/contract/$bookingId': typeof PublicContractBookingIdRoute
  '/payment/$bookingId': typeof PublicPaymentBookingIdRoute
  '/rent/bez-zaloga': typeof PublicRentBezZalogaRoute
  '/rent/novosibirsk': typeof PublicRentNovosibirskRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/cars/': typeof PublicCarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kei-cars': typeof PublicKeiCarsRoute
  '/privacy': typeof PublicPrivacyRoute
  '/profile': typeof PublicProfileRoute
  '/terms': typeof PublicTermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/bookings': typeof AdminAdminBookingsRoute
  '/admin/cars': typeof AdminAdminCarsRoute
  '/admin/clients': typeof AdminAdminClientsRoute
  '/admin/finance': typeof AdminAdminFinanceRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/booking/$carId': typeof PublicBookingCarIdRoute
  '/cars/$carId': typeof PublicCarsCarIdRoute
  '/contract/$bookingId': typeof PublicContractBookingIdRoute
  '/payment/$bookingId': typeof PublicPaymentBookingIdRoute
  '/rent/bez-zaloga': typeof PublicRentBezZalogaRoute
  '/rent/novosibirsk': typeof PublicRentNovosibirskRoute
  '/admin': typeof AdminAdminIndexRoute
  '/blog': typeof PublicBlogIndexRoute
  '/cars': typeof PublicCarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_public/kei-cars': typeof PublicKeiCarsRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/profile': typeof PublicProfileRoute
  '/_public/terms': typeof PublicTermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/_admin/admin/bookings': typeof AdminAdminBookingsRoute
  '/_admin/admin/cars': typeof AdminAdminCarsRoute
  '/_admin/admin/clients': typeof AdminAdminClientsRoute
  '/_admin/admin/finance': typeof AdminAdminFinanceRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_public/booking/$carId': typeof PublicBookingCarIdRoute
  '/_public/cars/$carId': typeof PublicCarsCarIdRoute
  '/_public/contract/$bookingId': typeof PublicContractBookingIdRoute
  '/_public/payment/$bookingId': typeof PublicPaymentBookingIdRoute
  '/_public/rent/bez-zaloga': typeof PublicRentBezZalogaRoute
  '/_public/rent/novosibirsk': typeof PublicRentNovosibirskRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/cars/': typeof PublicCarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/kei-cars'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/admin/login'
    | '/admin/bookings'
    | '/admin/cars'
    | '/admin/clients'
    | '/admin/finance'
    | '/admin/settings'
    | '/blog/$slug'
    | '/booking/$carId'
    | '/cars/$carId'
    | '/contract/$bookingId'
    | '/payment/$bookingId'
    | '/rent/bez-zaloga'
    | '/rent/novosibirsk'
    | '/admin/'
    | '/blog/'
    | '/cars/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/kei-cars'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/admin/login'
    | '/admin/bookings'
    | '/admin/cars'
    | '/admin/clients'
    | '/admin/finance'
    | '/admin/settings'
    | '/blog/$slug'
    | '/booking/$carId'
    | '/cars/$carId'
    | '/contract/$bookingId'
    | '/payment/$bookingId'
    | '/rent/bez-zaloga'
    | '/rent/novosibirsk'
    | '/admin'
    | '/blog'
    | '/cars'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_public'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_public/kei-cars'
    | '/_public/privacy'
    | '/_public/profile'
    | '/_public/terms'
    | '/admin/login'
    | '/_admin/admin/bookings'
    | '/_admin/admin/cars'
    | '/_admin/admin/clients'
    | '/_admin/admin/finance'
    | '/_admin/admin/settings'
    | '/_public/blog/$slug'
    | '/_public/booking/$carId'
    | '/_public/cars/$carId'
    | '/_public/contract/$bookingId'
    | '/_public/payment/$bookingId'
    | '/_public/rent/bez-zaloga'
    | '/_public/rent/novosibirsk'
    | '/_admin/admin/'
    | '/_public/blog/'
    | '/_public/cars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/profile': {
      id: '/_public/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PublicProfileRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/kei-cars': {
      id: '/_public/kei-cars'
      path: '/kei-cars'
      fullPath: '/kei-cars'
      preLoaderRoute: typeof PublicKeiCarsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cars/': {
      id: '/_public/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof PublicCarsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/rent/novosibirsk': {
      id: '/_public/rent/novosibirsk'
      path: '/rent/novosibirsk'
      fullPath: '/rent/novosibirsk'
      preLoaderRoute: typeof PublicRentNovosibirskRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/rent/bez-zaloga': {
      id: '/_public/rent/bez-zaloga'
      path: '/rent/bez-zaloga'
      fullPath: '/rent/bez-zaloga'
      preLoaderRoute: typeof PublicRentBezZalogaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/payment/$bookingId': {
      id: '/_public/payment/$bookingId'
      path: '/payment/$bookingId'
      fullPath: '/payment/$bookingId'
      preLoaderRoute: typeof PublicPaymentBookingIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contract/$bookingId': {
      id: '/_public/contract/$bookingId'
      path: '/contract/$bookingId'
      fullPath: '/contract/$bookingId'
      preLoaderRoute: typeof PublicContractBookingIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cars/$carId': {
      id: '/_public/cars/$carId'
      path: '/cars/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof PublicCarsCarIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/booking/$carId': {
      id: '/_public/booking/$carId'
      path: '/booking/$carId'
      fullPath: '/booking/$carId'
      preLoaderRoute: typeof PublicBookingCarIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/finance': {
      id: '/_admin/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminAdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/clients': {
      id: '/_admin/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminAdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/cars': {
      id: '/_admin/admin/cars'
      path: '/admin/cars'
      fullPath: '/admin/cars'
      preLoaderRoute: typeof AdminAdminCarsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/bookings': {
      id: '/_admin/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminAdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminBookingsRoute: typeof AdminAdminBookingsRoute
  AdminAdminCarsRoute: typeof AdminAdminCarsRoute
  AdminAdminClientsRoute: typeof AdminAdminClientsRoute
  AdminAdminFinanceRoute: typeof AdminAdminFinanceRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminBookingsRoute: AdminAdminBookingsRoute,
  AdminAdminCarsRoute: AdminAdminCarsRoute,
  AdminAdminClientsRoute: AdminAdminClientsRoute,
  AdminAdminFinanceRoute: AdminAdminFinanceRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PublicRouteChildren {
  PublicKeiCarsRoute: typeof PublicKeiCarsRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicProfileRoute: typeof PublicProfileRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicBookingCarIdRoute: typeof PublicBookingCarIdRoute
  PublicCarsCarIdRoute: typeof PublicCarsCarIdRoute
  PublicContractBookingIdRoute: typeof PublicContractBookingIdRoute
  PublicPaymentBookingIdRoute: typeof PublicPaymentBookingIdRoute
  PublicRentBezZalogaRoute: typeof PublicRentBezZalogaRoute
  PublicRentNovosibirskRoute: typeof PublicRentNovosibirskRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicCarsIndexRoute: typeof PublicCarsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicKeiCarsRoute: PublicKeiCarsRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicProfileRoute: PublicProfileRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicBookingCarIdRoute: PublicBookingCarIdRoute,
  PublicCarsCarIdRoute: PublicCarsCarIdRoute,
  PublicContractBookingIdRoute: PublicContractBookingIdRoute,
  PublicPaymentBookingIdRoute: PublicPaymentBookingIdRoute,
  PublicRentBezZalogaRoute: PublicRentBezZalogaRoute,
  PublicRentNovosibirskRoute: PublicRentNovosibirskRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicCarsIndexRoute: PublicCarsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
