/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as PublicTermsRouteImport } from './routes/_public.terms'
import { Route as PublicProfileRouteImport } from './routes/_public.profile'
import { Route as PublicPrivacyRouteImport } from './routes/_public.privacy'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as PublicKeiCarsRouteImport } from './routes/_public.kei-cars'
import { Route as PublicArendaProbegIPlatezhiRouteImport } from './routes/_public.arenda-probeg-i-platezhi'
import { Route as PublicArendaAvtoVyhodnyeRouteImport } from './routes/_public.arenda-avto-vyhodnye'
import { Route as PublicArendaAvtoSPravymRulemRouteImport } from './routes/_public.arenda-avto-s-pravym-rulem'
import { Route as PublicArendaAvtoPoezdkaAltayRouteImport } from './routes/_public.arenda-avto-poezdka-altay'
import { Route as PublicArendaAvtoNaSutkiRouteImport } from './routes/_public.arenda-avto-na-sutki'
import { Route as PublicArendaAvtoNaNedelyuRouteImport } from './routes/_public.arenda-avto-na-nedelyu'
import { Route as PublicArendaAvtoNaMesyacRouteImport } from './routes/_public.arenda-avto-na-mesyac'
import { Route as PublicArendaAvtoBezZalogaRouteImport } from './routes/_public.arenda-avto-bez-zaloga'
import { Route as PublicArendaAvtoBezVoditelyaRouteImport } from './routes/_public.arenda-avto-bez-voditelya'
import { Route as PublicArendaAvtoBezStazhaRouteImport } from './routes/_public.arenda-avto-bez-stazha'
import { Route as PublicCarsIndexRouteImport } from './routes/_public.cars.index'
import { Route as PublicBlogIndexRouteImport } from './routes/_public.blog.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as ApiPublicYookassaWebhookRouteImport } from './routes/api/public/yookassa-webhook'
import { Route as ApiPublicVersionRouteImport } from './routes/api/public/version'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as PublicRentNovosibirskRouteImport } from './routes/_public.rent.novosibirsk'
import { Route as PublicRentBezZalogaRouteImport } from './routes/_public.rent.bez-zaloga'
import { Route as PublicPaymentBookingIdRouteImport } from './routes/_public.payment.$bookingId'
import { Route as PublicContractBookingIdRouteImport } from './routes/_public.contract.$bookingId'
import { Route as PublicCarsCarIdRouteImport } from './routes/_public.cars.$carId'
import { Route as PublicBookingCarIdRouteImport } from './routes/_public.booking.$carId'
import { Route as PublicBlogSlugRouteImport } from './routes/_public.blog.$slug'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin.admin.settings'
import { Route as AdminAdminFinanceRouteImport } from './routes/_admin.admin.finance'
import { Route as AdminAdminClientsRouteImport } from './routes/_admin.admin.clients'
import { Route as AdminAdminCarsRouteImport } from './routes/_admin.admin.cars'
import { Route as AdminAdminBookingsRouteImport } from './routes/_admin.admin.bookings'
import { Route as AdminAdminCarPhotosCarIdRouteImport } from './routes/_admin.admin.car-photos.$carId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProfileRoute = PublicProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicKeiCarsRoute = PublicKeiCarsRouteImport.update({
  id: '/kei-cars',
  path: '/kei-cars',
  getParentRoute: () => PublicRoute,
} as any)
const PublicArendaProbegIPlatezhiRoute =
  PublicArendaProbegIPlatezhiRouteImport.update({
    id: '/arenda-probeg-i-platezhi',
    path: '/arenda-probeg-i-platezhi',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicArendaAvtoVyhodnyeRoute =
  PublicArendaAvtoVyhodnyeRouteImport.update({
    id: '/arenda-avto-vyhodnye',
    path: '/arenda-avto-vyhodnye',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicArendaAvtoSPravymRulemRoute =
  PublicArendaAvtoSPravymRulemRouteImport.update({
    id: '/arenda-avto-s-pravym-rulem',
    path: '/arenda-avto-s-pravym-rulem',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicArendaAvtoPoezdkaAltayRoute =
  PublicArendaAvtoPoezdkaAltayRouteImport.update({
    id: '/arenda-avto-poezdka-altay',
    path: '/arenda-avto-poezdka-altay',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicArendaAvtoNaSutkiRoute = PublicArendaAvtoNaSutkiRouteImport.update({
  id: '/arenda-avto-na-sutki',
  path: '/arenda-avto-na-sutki',
  getParentRoute: () => PublicRoute,
} as any)
const PublicArendaAvtoNaNedelyuRoute =
  PublicArendaAvtoNaNedelyuRouteImport.update({
    id: '/arenda-avto-na-nedelyu',
    path: '/arenda-avto-na-nedelyu',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicArendaAvtoNaMesyacRoute =
  PublicArendaAvtoNaMesyacRouteImport.update({
    id: '/arenda-avto-na-mesyac',
    path: '/arenda-avto-na-mesyac',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicArendaAvtoBezZalogaRoute =
  PublicArendaAvtoBezZalogaRouteImport.update({
    id: '/arenda-avto-bez-zaloga',
    path: '/arenda-avto-bez-zaloga',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicArendaAvtoBezVoditelyaRoute =
  PublicArendaAvtoBezVoditelyaRouteImport.update({
    id: '/arenda-avto-bez-voditelya',
    path: '/arenda-avto-bez-voditelya',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicArendaAvtoBezStazhaRoute =
  PublicArendaAvtoBezStazhaRouteImport.update({
    id: '/arenda-avto-bez-stazha',
    path: '/arenda-avto-bez-stazha',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicCarsIndexRoute = PublicCarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicYookassaWebhookRoute =
  ApiPublicYookassaWebhookRouteImport.update({
    id: '/api/public/yookassa-webhook',
    path: '/api/public/yookassa-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVersionRoute = ApiPublicVersionRouteImport.update({
  id: '/api/public/version',
  path: '/api/public/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRentNovosibirskRoute = PublicRentNovosibirskRouteImport.update({
  id: '/rent/novosibirsk',
  path: '/rent/novosibirsk',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRentBezZalogaRoute = PublicRentBezZalogaRouteImport.update({
  id: '/rent/bez-zaloga',
  path: '/rent/bez-zaloga',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPaymentBookingIdRoute = PublicPaymentBookingIdRouteImport.update({
  id: '/payment/$bookingId',
  path: '/payment/$bookingId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContractBookingIdRoute = PublicContractBookingIdRouteImport.update({
  id: '/contract/$bookingId',
  path: '/contract/$bookingId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCarsCarIdRoute = PublicCarsCarIdRouteImport.update({
  id: '/cars/$carId',
  path: '/cars/$carId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBookingCarIdRoute = PublicBookingCarIdRouteImport.update({
  id: '/booking/$carId',
  path: '/booking/$carId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminFinanceRoute = AdminAdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminClientsRoute = AdminAdminClientsRouteImport.update({
  id: '/admin/clients',
  path: '/admin/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCarsRoute = AdminAdminCarsRouteImport.update({
  id: '/admin/cars',
  path: '/admin/cars',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBookingsRoute = AdminAdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCarPhotosCarIdRoute =
  AdminAdminCarPhotosCarIdRouteImport.update({
    id: '/admin/car-photos/$carId',
    path: '/admin/car-photos/$carId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/arenda-avto-bez-stazha': typeof PublicArendaAvtoBezStazhaRoute
  '/arenda-avto-bez-voditelya': typeof PublicArendaAvtoBezVoditelyaRoute
  '/arenda-avto-bez-zaloga': typeof PublicArendaAvtoBezZalogaRoute
  '/arenda-avto-na-mesyac': typeof PublicArendaAvtoNaMesyacRoute
  '/arenda-avto-na-nedelyu': typeof PublicArendaAvtoNaNedelyuRoute
  '/arenda-avto-na-sutki': typeof PublicArendaAvtoNaSutkiRoute
  '/arenda-avto-poezdka-altay': typeof PublicArendaAvtoPoezdkaAltayRoute
  '/arenda-avto-s-pravym-rulem': typeof PublicArendaAvtoSPravymRulemRoute
  '/arenda-avto-vyhodnye': typeof PublicArendaAvtoVyhodnyeRoute
  '/arenda-probeg-i-platezhi': typeof PublicArendaProbegIPlatezhiRoute
  '/kei-cars': typeof PublicKeiCarsRoute
  '/login': typeof PublicLoginRoute
  '/privacy': typeof PublicPrivacyRoute
  '/profile': typeof PublicProfileRoute
  '/terms': typeof PublicTermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/bookings': typeof AdminAdminBookingsRoute
  '/admin/cars': typeof AdminAdminCarsRoute
  '/admin/clients': typeof AdminAdminClientsRoute
  '/admin/finance': typeof AdminAdminFinanceRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/booking/$carId': typeof PublicBookingCarIdRoute
  '/cars/$carId': typeof PublicCarsCarIdRoute
  '/contract/$bookingId': typeof PublicContractBookingIdRoute
  '/payment/$bookingId': typeof PublicPaymentBookingIdRoute
  '/rent/bez-zaloga': typeof PublicRentBezZalogaRoute
  '/rent/novosibirsk': typeof PublicRentNovosibirskRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/api/public/yookassa-webhook': typeof ApiPublicYookassaWebhookRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/cars/': typeof PublicCarsIndexRoute
  '/admin/car-photos/$carId': typeof AdminAdminCarPhotosCarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/arenda-avto-bez-stazha': typeof PublicArendaAvtoBezStazhaRoute
  '/arenda-avto-bez-voditelya': typeof PublicArendaAvtoBezVoditelyaRoute
  '/arenda-avto-bez-zaloga': typeof PublicArendaAvtoBezZalogaRoute
  '/arenda-avto-na-mesyac': typeof PublicArendaAvtoNaMesyacRoute
  '/arenda-avto-na-nedelyu': typeof PublicArendaAvtoNaNedelyuRoute
  '/arenda-avto-na-sutki': typeof PublicArendaAvtoNaSutkiRoute
  '/arenda-avto-poezdka-altay': typeof PublicArendaAvtoPoezdkaAltayRoute
  '/arenda-avto-s-pravym-rulem': typeof PublicArendaAvtoSPravymRulemRoute
  '/arenda-avto-vyhodnye': typeof PublicArendaAvtoVyhodnyeRoute
  '/arenda-probeg-i-platezhi': typeof PublicArendaProbegIPlatezhiRoute
  '/kei-cars': typeof PublicKeiCarsRoute
  '/login': typeof PublicLoginRoute
  '/privacy': typeof PublicPrivacyRoute
  '/profile': typeof PublicProfileRoute
  '/terms': typeof PublicTermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/bookings': typeof AdminAdminBookingsRoute
  '/admin/cars': typeof AdminAdminCarsRoute
  '/admin/clients': typeof AdminAdminClientsRoute
  '/admin/finance': typeof AdminAdminFinanceRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/booking/$carId': typeof PublicBookingCarIdRoute
  '/cars/$carId': typeof PublicCarsCarIdRoute
  '/contract/$bookingId': typeof PublicContractBookingIdRoute
  '/payment/$bookingId': typeof PublicPaymentBookingIdRoute
  '/rent/bez-zaloga': typeof PublicRentBezZalogaRoute
  '/rent/novosibirsk': typeof PublicRentNovosibirskRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/api/public/yookassa-webhook': typeof ApiPublicYookassaWebhookRoute
  '/admin': typeof AdminAdminIndexRoute
  '/blog': typeof PublicBlogIndexRoute
  '/cars': typeof PublicCarsIndexRoute
  '/admin/car-photos/$carId': typeof AdminAdminCarPhotosCarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_public/arenda-avto-bez-stazha': typeof PublicArendaAvtoBezStazhaRoute
  '/_public/arenda-avto-bez-voditelya': typeof PublicArendaAvtoBezVoditelyaRoute
  '/_public/arenda-avto-bez-zaloga': typeof PublicArendaAvtoBezZalogaRoute
  '/_public/arenda-avto-na-mesyac': typeof PublicArendaAvtoNaMesyacRoute
  '/_public/arenda-avto-na-nedelyu': typeof PublicArendaAvtoNaNedelyuRoute
  '/_public/arenda-avto-na-sutki': typeof PublicArendaAvtoNaSutkiRoute
  '/_public/arenda-avto-poezdka-altay': typeof PublicArendaAvtoPoezdkaAltayRoute
  '/_public/arenda-avto-s-pravym-rulem': typeof PublicArendaAvtoSPravymRulemRoute
  '/_public/arenda-avto-vyhodnye': typeof PublicArendaAvtoVyhodnyeRoute
  '/_public/arenda-probeg-i-platezhi': typeof PublicArendaProbegIPlatezhiRoute
  '/_public/kei-cars': typeof PublicKeiCarsRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/profile': typeof PublicProfileRoute
  '/_public/terms': typeof PublicTermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/_admin/admin/bookings': typeof AdminAdminBookingsRoute
  '/_admin/admin/cars': typeof AdminAdminCarsRoute
  '/_admin/admin/clients': typeof AdminAdminClientsRoute
  '/_admin/admin/finance': typeof AdminAdminFinanceRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_public/booking/$carId': typeof PublicBookingCarIdRoute
  '/_public/cars/$carId': typeof PublicCarsCarIdRoute
  '/_public/contract/$bookingId': typeof PublicContractBookingIdRoute
  '/_public/payment/$bookingId': typeof PublicPaymentBookingIdRoute
  '/_public/rent/bez-zaloga': typeof PublicRentBezZalogaRoute
  '/_public/rent/novosibirsk': typeof PublicRentNovosibirskRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/api/public/yookassa-webhook': typeof ApiPublicYookassaWebhookRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/cars/': typeof PublicCarsIndexRoute
  '/_admin/admin/car-photos/$carId': typeof AdminAdminCarPhotosCarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/arenda-avto-bez-stazha'
    | '/arenda-avto-bez-voditelya'
    | '/arenda-avto-bez-zaloga'
    | '/arenda-avto-na-mesyac'
    | '/arenda-avto-na-nedelyu'
    | '/arenda-avto-na-sutki'
    | '/arenda-avto-poezdka-altay'
    | '/arenda-avto-s-pravym-rulem'
    | '/arenda-avto-vyhodnye'
    | '/arenda-probeg-i-platezhi'
    | '/kei-cars'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/admin/login'
    | '/admin/bookings'
    | '/admin/cars'
    | '/admin/clients'
    | '/admin/finance'
    | '/admin/settings'
    | '/blog/$slug'
    | '/booking/$carId'
    | '/cars/$carId'
    | '/contract/$bookingId'
    | '/payment/$bookingId'
    | '/rent/bez-zaloga'
    | '/rent/novosibirsk'
    | '/api/public/health'
    | '/api/public/version'
    | '/api/public/yookassa-webhook'
    | '/admin/'
    | '/blog/'
    | '/cars/'
    | '/admin/car-photos/$carId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/arenda-avto-bez-stazha'
    | '/arenda-avto-bez-voditelya'
    | '/arenda-avto-bez-zaloga'
    | '/arenda-avto-na-mesyac'
    | '/arenda-avto-na-nedelyu'
    | '/arenda-avto-na-sutki'
    | '/arenda-avto-poezdka-altay'
    | '/arenda-avto-s-pravym-rulem'
    | '/arenda-avto-vyhodnye'
    | '/arenda-probeg-i-platezhi'
    | '/kei-cars'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/terms'
    | '/admin/login'
    | '/admin/bookings'
    | '/admin/cars'
    | '/admin/clients'
    | '/admin/finance'
    | '/admin/settings'
    | '/blog/$slug'
    | '/booking/$carId'
    | '/cars/$carId'
    | '/contract/$bookingId'
    | '/payment/$bookingId'
    | '/rent/bez-zaloga'
    | '/rent/novosibirsk'
    | '/api/public/health'
    | '/api/public/version'
    | '/api/public/yookassa-webhook'
    | '/admin'
    | '/blog'
    | '/cars'
    | '/admin/car-photos/$carId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_public'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_public/arenda-avto-bez-stazha'
    | '/_public/arenda-avto-bez-voditelya'
    | '/_public/arenda-avto-bez-zaloga'
    | '/_public/arenda-avto-na-mesyac'
    | '/_public/arenda-avto-na-nedelyu'
    | '/_public/arenda-avto-na-sutki'
    | '/_public/arenda-avto-poezdka-altay'
    | '/_public/arenda-avto-s-pravym-rulem'
    | '/_public/arenda-avto-vyhodnye'
    | '/_public/arenda-probeg-i-platezhi'
    | '/_public/kei-cars'
    | '/_public/login'
    | '/_public/privacy'
    | '/_public/profile'
    | '/_public/terms'
    | '/admin/login'
    | '/_admin/admin/bookings'
    | '/_admin/admin/cars'
    | '/_admin/admin/clients'
    | '/_admin/admin/finance'
    | '/_admin/admin/settings'
    | '/_public/blog/$slug'
    | '/_public/booking/$carId'
    | '/_public/cars/$carId'
    | '/_public/contract/$bookingId'
    | '/_public/payment/$bookingId'
    | '/_public/rent/bez-zaloga'
    | '/_public/rent/novosibirsk'
    | '/api/public/health'
    | '/api/public/version'
    | '/api/public/yookassa-webhook'
    | '/_admin/admin/'
    | '/_public/blog/'
    | '/_public/cars/'
    | '/_admin/admin/car-photos/$carId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicVersionRoute: typeof ApiPublicVersionRoute
  ApiPublicYookassaWebhookRoute: typeof ApiPublicYookassaWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/profile': {
      id: '/_public/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PublicProfileRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/kei-cars': {
      id: '/_public/kei-cars'
      path: '/kei-cars'
      fullPath: '/kei-cars'
      preLoaderRoute: typeof PublicKeiCarsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/arenda-probeg-i-platezhi': {
      id: '/_public/arenda-probeg-i-platezhi'
      path: '/arenda-probeg-i-platezhi'
      fullPath: '/arenda-probeg-i-platezhi'
      preLoaderRoute: typeof PublicArendaProbegIPlatezhiRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/arenda-avto-vyhodnye': {
      id: '/_public/arenda-avto-vyhodnye'
      path: '/arenda-avto-vyhodnye'
      fullPath: '/arenda-avto-vyhodnye'
      preLoaderRoute: typeof PublicArendaAvtoVyhodnyeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/arenda-avto-s-pravym-rulem': {
      id: '/_public/arenda-avto-s-pravym-rulem'
      path: '/arenda-avto-s-pravym-rulem'
      fullPath: '/arenda-avto-s-pravym-rulem'
      preLoaderRoute: typeof PublicArendaAvtoSPravymRulemRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/arenda-avto-poezdka-altay': {
      id: '/_public/arenda-avto-poezdka-altay'
      path: '/arenda-avto-poezdka-altay'
      fullPath: '/arenda-avto-poezdka-altay'
      preLoaderRoute: typeof PublicArendaAvtoPoezdkaAltayRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/arenda-avto-na-sutki': {
      id: '/_public/arenda-avto-na-sutki'
      path: '/arenda-avto-na-sutki'
      fullPath: '/arenda-avto-na-sutki'
      preLoaderRoute: typeof PublicArendaAvtoNaSutkiRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/arenda-avto-na-nedelyu': {
      id: '/_public/arenda-avto-na-nedelyu'
      path: '/arenda-avto-na-nedelyu'
      fullPath: '/arenda-avto-na-nedelyu'
      preLoaderRoute: typeof PublicArendaAvtoNaNedelyuRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/arenda-avto-na-mesyac': {
      id: '/_public/arenda-avto-na-mesyac'
      path: '/arenda-avto-na-mesyac'
      fullPath: '/arenda-avto-na-mesyac'
      preLoaderRoute: typeof PublicArendaAvtoNaMesyacRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/arenda-avto-bez-zaloga': {
      id: '/_public/arenda-avto-bez-zaloga'
      path: '/arenda-avto-bez-zaloga'
      fullPath: '/arenda-avto-bez-zaloga'
      preLoaderRoute: typeof PublicArendaAvtoBezZalogaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/arenda-avto-bez-voditelya': {
      id: '/_public/arenda-avto-bez-voditelya'
      path: '/arenda-avto-bez-voditelya'
      fullPath: '/arenda-avto-bez-voditelya'
      preLoaderRoute: typeof PublicArendaAvtoBezVoditelyaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/arenda-avto-bez-stazha': {
      id: '/_public/arenda-avto-bez-stazha'
      path: '/arenda-avto-bez-stazha'
      fullPath: '/arenda-avto-bez-stazha'
      preLoaderRoute: typeof PublicArendaAvtoBezStazhaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cars/': {
      id: '/_public/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof PublicCarsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/yookassa-webhook': {
      id: '/api/public/yookassa-webhook'
      path: '/api/public/yookassa-webhook'
      fullPath: '/api/public/yookassa-webhook'
      preLoaderRoute: typeof ApiPublicYookassaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/version': {
      id: '/api/public/version'
      path: '/api/public/version'
      fullPath: '/api/public/version'
      preLoaderRoute: typeof ApiPublicVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/rent/novosibirsk': {
      id: '/_public/rent/novosibirsk'
      path: '/rent/novosibirsk'
      fullPath: '/rent/novosibirsk'
      preLoaderRoute: typeof PublicRentNovosibirskRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/rent/bez-zaloga': {
      id: '/_public/rent/bez-zaloga'
      path: '/rent/bez-zaloga'
      fullPath: '/rent/bez-zaloga'
      preLoaderRoute: typeof PublicRentBezZalogaRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/payment/$bookingId': {
      id: '/_public/payment/$bookingId'
      path: '/payment/$bookingId'
      fullPath: '/payment/$bookingId'
      preLoaderRoute: typeof PublicPaymentBookingIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contract/$bookingId': {
      id: '/_public/contract/$bookingId'
      path: '/contract/$bookingId'
      fullPath: '/contract/$bookingId'
      preLoaderRoute: typeof PublicContractBookingIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cars/$carId': {
      id: '/_public/cars/$carId'
      path: '/cars/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof PublicCarsCarIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/booking/$carId': {
      id: '/_public/booking/$carId'
      path: '/booking/$carId'
      fullPath: '/booking/$carId'
      preLoaderRoute: typeof PublicBookingCarIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/finance': {
      id: '/_admin/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminAdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/clients': {
      id: '/_admin/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminAdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/cars': {
      id: '/_admin/admin/cars'
      path: '/admin/cars'
      fullPath: '/admin/cars'
      preLoaderRoute: typeof AdminAdminCarsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/bookings': {
      id: '/_admin/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminAdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/car-photos/$carId': {
      id: '/_admin/admin/car-photos/$carId'
      path: '/admin/car-photos/$carId'
      fullPath: '/admin/car-photos/$carId'
      preLoaderRoute: typeof AdminAdminCarPhotosCarIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminBookingsRoute: typeof AdminAdminBookingsRoute
  AdminAdminCarsRoute: typeof AdminAdminCarsRoute
  AdminAdminClientsRoute: typeof AdminAdminClientsRoute
  AdminAdminFinanceRoute: typeof AdminAdminFinanceRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminCarPhotosCarIdRoute: typeof AdminAdminCarPhotosCarIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminBookingsRoute: AdminAdminBookingsRoute,
  AdminAdminCarsRoute: AdminAdminCarsRoute,
  AdminAdminClientsRoute: AdminAdminClientsRoute,
  AdminAdminFinanceRoute: AdminAdminFinanceRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminCarPhotosCarIdRoute: AdminAdminCarPhotosCarIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PublicRouteChildren {
  PublicArendaAvtoBezStazhaRoute: typeof PublicArendaAvtoBezStazhaRoute
  PublicArendaAvtoBezVoditelyaRoute: typeof PublicArendaAvtoBezVoditelyaRoute
  PublicArendaAvtoBezZalogaRoute: typeof PublicArendaAvtoBezZalogaRoute
  PublicArendaAvtoNaMesyacRoute: typeof PublicArendaAvtoNaMesyacRoute
  PublicArendaAvtoNaNedelyuRoute: typeof PublicArendaAvtoNaNedelyuRoute
  PublicArendaAvtoNaSutkiRoute: typeof PublicArendaAvtoNaSutkiRoute
  PublicArendaAvtoPoezdkaAltayRoute: typeof PublicArendaAvtoPoezdkaAltayRoute
  PublicArendaAvtoSPravymRulemRoute: typeof PublicArendaAvtoSPravymRulemRoute
  PublicArendaAvtoVyhodnyeRoute: typeof PublicArendaAvtoVyhodnyeRoute
  PublicArendaProbegIPlatezhiRoute: typeof PublicArendaProbegIPlatezhiRoute
  PublicKeiCarsRoute: typeof PublicKeiCarsRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicProfileRoute: typeof PublicProfileRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicBookingCarIdRoute: typeof PublicBookingCarIdRoute
  PublicCarsCarIdRoute: typeof PublicCarsCarIdRoute
  PublicContractBookingIdRoute: typeof PublicContractBookingIdRoute
  PublicPaymentBookingIdRoute: typeof PublicPaymentBookingIdRoute
  PublicRentBezZalogaRoute: typeof PublicRentBezZalogaRoute
  PublicRentNovosibirskRoute: typeof PublicRentNovosibirskRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicCarsIndexRoute: typeof PublicCarsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicArendaAvtoBezStazhaRoute: PublicArendaAvtoBezStazhaRoute,
  PublicArendaAvtoBezVoditelyaRoute: PublicArendaAvtoBezVoditelyaRoute,
  PublicArendaAvtoBezZalogaRoute: PublicArendaAvtoBezZalogaRoute,
  PublicArendaAvtoNaMesyacRoute: PublicArendaAvtoNaMesyacRoute,
  PublicArendaAvtoNaNedelyuRoute: PublicArendaAvtoNaNedelyuRoute,
  PublicArendaAvtoNaSutkiRoute: PublicArendaAvtoNaSutkiRoute,
  PublicArendaAvtoPoezdkaAltayRoute: PublicArendaAvtoPoezdkaAltayRoute,
  PublicArendaAvtoSPravymRulemRoute: PublicArendaAvtoSPravymRulemRoute,
  PublicArendaAvtoVyhodnyeRoute: PublicArendaAvtoVyhodnyeRoute,
  PublicArendaProbegIPlatezhiRoute: PublicArendaProbegIPlatezhiRoute,
  PublicKeiCarsRoute: PublicKeiCarsRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicProfileRoute: PublicProfileRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicBookingCarIdRoute: PublicBookingCarIdRoute,
  PublicCarsCarIdRoute: PublicCarsCarIdRoute,
  PublicContractBookingIdRoute: PublicContractBookingIdRoute,
  PublicPaymentBookingIdRoute: PublicPaymentBookingIdRoute,
  PublicRentBezZalogaRoute: PublicRentBezZalogaRoute,
  PublicRentNovosibirskRoute: PublicRentNovosibirskRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicCarsIndexRoute: PublicCarsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicVersionRoute: ApiPublicVersionRoute,
  ApiPublicYookassaWebhookRoute: ApiPublicYookassaWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
